extends:
  - airbnb-base
  - eslint-config-prettier
rules:
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
  import/extensions:
    - error
    - js: always
      json: always
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    classes: true
    jsx: true
