extends:
  - airbnb-base
  - eslint-config-prettier
  - plugin:jest/recommended
rules:
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - src/tests/**
