extends:
  - airbnb-base
  - eslint-config-prettier
  - plugin:jest/recommended
rules:
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
  import/extensions:
    - error
    - js: always
      json: always
  import/prefer-default-export:
    - off
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - src/tests/**
